export default {
    FETCH_EVIDENCE_REQUEST:'FETCH_EVIDENCE_REQUEST',
    FETCH_EVIDENCE_SUCCESSFUL:'FETCH_EVIDENCE_SUCCESSFUL',
    FETCH_EVIDENCE_FAILED:'FETCH_EVIDENCE_FAILED',

    SELECT_EVIDENCE_FROM_MAP:'SELECT_EVIDENCE_FROM_MAP',
    SELECT_IMAGE_FROM_SIDEBAR: 'SELECT_IMAGE_FROM_SIDEBAR',

    CLOSE_MODAL: "CLOSE_MODAL"
}